#!/bin/bash
touch .env
echo VITE_MILLICAST_STREAM_NAME=${{ secrets.MILLICAST_STREAM_NAME }} >> .env
echo VITE_MILLICAST_STREAM_PUBLISHING_TOKEN=${{ secrets.STREAM_PUBLISHING_TOKEN }} >> .env
echo VITE_MILLICAST_STREAM_ACCOUNT_ID=${{secrets.STREAM_ACCOUNT_ID }} >> .env
