settings popup: '//*[@test-id="streamSettingsPopoverHeading"]/parent::*'
settings title: '[test-id=streamSettingsPopoverHeading]'
settings dropdowns:
  - '$ref: settings popup'
  - '[test-id*=SelectDefault]'
source name label:
  - '$ref: settings popup'
  - '[test-id=sourceName] label'
source name input:
  - '$ref: settings popup'
  - '[test-id=sourceName] input'
codec dropdown:
  - '$ref: settings popup'
  - '[test-id=codecSelectDefault]'
codec dropdown default: '$ref: codec dropdown'
codec dropdown options:
  - '$ref: settings popup'
  - '[test-id=codecSelectOptions]'
resolution dropdown:
  - '$ref: settings popup'
  - '[test-id=resolutionSelectDefault]'
resolution dropdown default: '$ref: resolution dropdown'
resolution dropdown options:
  - '$ref: settings popup'  
  - '[test-id=resolutionSelectOptions]'
bitrate dropdown:
  - '$ref: settings popup'
  - '[test-id=bitrateSelectDefault]'
bitrate dropdown default: '$ref: bitrate dropdown'
bitrate dropdown options:
  - '$ref: settings popup'
  - '[test-id=bitrateSelectOptions]'
quality dropdown:
  - '$ref: settings popup'
  - '[test-id=qualitySelectDefault]'
quality dropdown default: '$ref: quality dropdown'
quality dropdown options:
  - '$ref: settings popup'
  - '[test-id=qualitySelectOptions]'
simulcast label:
  - '$ref: settings popup'
  - '[test-id=simulcastToggle] p'
simulcast switch:
  - '$ref: settings popup'
  - '[test-id=simulcastToggle] input'
simulcast: '$ref: simulcast switch'
settings close button:
  - '$ref: settings popup'
  - '[test-id=streamSettingsPopoverCloseButton]'


# camera view settings:
#   - '$ref: camera view container'
#   - '$ref: settings'
# camera view settings title:
#   - '$ref: camera view container'
#   - '$ref: settings title'
# camera view settings dropdowns:
#   - '$ref: camera view container'
#   - '$ref: settings dropdowns'
# camera view source name input:
#   - '$ref: camera view container'
#   - '$ref: source name input'
# camera view codec dropdown:
#   - '$ref: camera view container'
#   - '$ref: codec dropdown'
# camera view codec dropdown default: '$ref: camera view codec dropdown'
# camera view codec dropdown options:
#   - '$ref: camera view container'
#   - '$ref: codec dropdown options'
# camera view resolution dropdown:
#   - '$ref: camera view container'
#   - '$ref: resolution dropdown'
# camera view resolution dropdown default: '$ref: camera view resolution dropdown'
# camera view resolution dropdown options:
#   - '$ref: camera view container'
#   - '$ref: resolution dropdown options'
# camera view bitrate dropdown:
#   - '$ref: camera view container'
#   - '$ref: bitrate dropdown'
# camera view bitrate dropdown default: '$ref: camera view bitrate dropdown'
# camera view bitrate dropdown options:
#   - '$ref: camera view container'
#   - '$ref: bitrate dropdown options'
# camera view simulcast label:
#   - '$ref: camera view container'
#   - '$ref: simulcast label'
# camera view simulcast switch:
#   - '$ref: camera view container'
#   - '$ref: simulcast switch'
# camera view simulcast: '$ref: camera view simulcast switch'
# camera view quality dropdown:
#   - '$ref: camera view container'
#   - '$ref: quality dropdown'
# camera view quality dropdown default: '$ref: camera view quality dropdown'
# camera view quality dropdown options:
#   - '$ref: camera view container'
#   - '$ref: quality dropdown options'
# camera view settings close button:
#   - '$ref: camera view container'
#   - '$ref: settings close button'


# screen view settings:
#   - '$ref: screen view container'
#   - '$ref: settings'
# screen view settings title:
#   - '$ref: screen view container'
#   - '$ref: settings title'
# screen view settings dropdowns:
#   - '$ref: screen view container'
#   - '$ref: settings dropdowns'
# screen view source name input:
#   - '$ref: screen view container'
#   - '$ref: source name input'
# screen view codec dropdown:
#   - '$ref: screen view container'
#   - '$ref: codec dropdown'
# screen view codec dropdown default: '$ref: screen view codec dropdown'
# screen view codec dropdown options:
#   - '$ref: screen view container'
#   - '$ref: codec dropdown options'
# screen view resolution dropdown:
#   - '$ref: screen view container'
#   - '$ref: resolution dropdown'
# screen view resolution dropdown default: '$ref: screen view resolution dropdown'
# screen view resolution dropdown options:
#   - '$ref: screen view container'
#   - '$ref: resolution dropdown options'
# screen view bitrate dropdown:
#   - '$ref: screen view container'
#   - '$ref: bitrate dropdown'
# screen view bitrate dropdown default: '$ref: screen view bitrate dropdown'
# screen view bitrate dropdown options:
#   - '$ref: screen view container'
#   - '$ref: bitrate dropdown options'
# screen view simulcast label:
#   - '$ref: screen view container'
#   - '$ref: simulcast label'
# screen view simulcast switch:
#   - '$ref: screen view container'
#   - '$ref: simulcast switch'
# screen view simulcast: '$ref: screen view simulcast switch'
# screen view quality dropdown:
#   - '$ref: screen view container'
#   - '$ref: quality dropdown'
# screen view quality dropdown default: '$ref: screen view quality dropdown'
# screen view quality dropdown options:
#   - '$ref: screen view container'
#   - '$ref: quality dropdown options'
# screen view settings close button:
#   - '$ref: screen view container'
#   - '$ref: settings close button'