export { default as IconCameraOn } from './Camera';
export { default as IconCameraOff } from './CameraOff';
export { default as IconFullScreen } from './FullScreen';
export { default as IconFullScreenExit } from './FullScreenExit';
export { default as IconMicrophoneOn } from './Microphone';
export { default as IconMicrophoneOff } from './MicrophoneOff';
export { default as IconSettings } from './Settings';
export { default as IconParicipant } from './Participants';
export { default as IconInfo } from './Info';
